### ISSUE TITLE
IotHubConnectionStateCallback not working with HTTPS, MQTT

### ISSUE THREAD

**Issue by jkriba** [Azure/azure-iot-sdk-java#106]
Hi Support,
  We are using Android Version 7.1 for developing a Cloud connector for our business application in the mobile device. We were trying to use the IotHubConnectionStateCallback API to get to know the IoT Hub Connection status since we can avoid write our own connection Monitor functionality. But the IotHubConnectionStateCallback API is totally not working for HTTPS or MQTT.

- **OS and version used:** <VERSION>Android 7.1 

- **Java runtime used:** <VERSION> JDK "1.8.0_45" 

- **SDK version used:** <VERSION>  IoT Device Client 1.3.29 for Java

# Description of the issue:
IotHubConnectionStateCallback API is not working with HTTPS , MQTT hence we were not able to have a common connection monitor implementation in the Android Cloud Connector.

**Comment by prmathur-microsoft** [comment]
Connection status callback is currently supported only for AMQPS and AMQPS_WS. It is in our backlog to implement this

**Comment by prmathur-microsoft** [comment]
In meantime, please feel free to provide a PR and we will take it in.

**Comment by timtay-microsoft** [comment]
Connection status callback is now supported for all protocols, but I recommend you use the newly added [connection status change callback API](https://github.com/Azure/azure-iot-sdk-java/blob/bf8af7107a0ea2795bb13b6b91342825bd4f1016/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java#L1239)

I'm going to close this issue since this was fixed a while ago. Sorry for not responding to this thread earlier.
