### ISSUE TITLE
Question: DeviceClient.Create in java ?

### ISSUE THREAD

**Issue by ApiO** [Azure/azure-iot-sdk-java#111]
Hi,

In C# sdk there is a Create function allowing us to instantiate a client like this:

```
DeviceClient deviceClient = DeviceClient.Create(
                 "IOT_HUB_HOSTNAME",
                 new DeviceAuthenticationWithRegistrySymmetricKey("deviceId", "primaryKey||secondaryKey"),
                 TransportType.Mqtt);
```
From device sdk `com.microsoft.azure.sdk.iot, iot-device-client, 1.3.29` is there a way to do the same thing ?

Regards.

**Comment by prmathur-microsoft** [comment]
Can I understand your scenario little better ? Java currently provides DeviceClient class where you can use constructor of this class to create a object using Connection String. 

DeviceClient client = new DeviceClient(connString, protocol);

Does this work for you ? Because connection string is a set of hotName, deviceid, device key in the format as below : 
Connection String : 
HostName=<HostName>;DeviceId=<Device ID>;SharedAccessKey=<key value>

**Comment by ApiO** [comment]
Oh my -_- ... I read "SharedAccessName" ... not key, time to sleep, so this is it.
Sorry and thanks for the reply. 👍
