### ISSUE TITLE
[Technical Question] Wondering why a device using gateway hostname in connection string is considered as an edge hub

### ISSUE THREAD

**Issue by zonble** [Azure/azure-iot-sdk-java#1561]
Hi,

recently my company is building a service on the top of Azure IoT Hub. We use the Java SDK to let the devices to connect to IoT Hub and receive C2D messages. 

Due to our internal security guideline, our infra guys ask us to build a gateway between the end devices and IoT Hub, so we added the gateway hostname setting in the connection string when building an instance of DeviceClient.

Then, we noticed that our devices did not receive any message from MQTT connections. We found that there is a member variable "isEdgeHub" in the MqttMessaging class, and an MqttMessaging does not subscribe to MQTT topics when the variable is true.

https://github.com/Azure/azure-iot-sdk-java/blob/04227edbe61663d3bbc65a128a927eda730ae042/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessaging.java#L63-L66

The the variable is set to true when the gateway hostname is not empty.

https://github.com/Azure/azure-iot-sdk-java/blob/1a71438288f71761432186db68a5e6f11a8ef4e3/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java#L219-L226

Currently we forked the repo to make the devices to always subscribe MQTT topics, but I am somehow quite confused about the API design. My opinion is, whether a device should subscribe to MQTT topics should be controlled by the SDK user or in the IoT Hub portal, but now it controlled by of there is a gateway hostname or not. I do not understand why.

We also noticed that even a client does not subscribe to the MQTT topics, but the queued C2D messages are also cleared when an MQTT connection is built. The behavior is also confusing, since the queue is cleared but the client actually receives nothing.

I do appreciate if you can answer my question, thanks!

**Comment by timtay-microsoft** [comment]
The gateway host name is only typically provided when acting as an edge module communicating with an Azure IoT Edgehub instance, so that is why the SDK makes some assumptions about which MQTT topics to subscribe to based on if it is provided or not.

If you are trying to communicate with IoT Hub through an HTTP proxy, then you don't need to provide a gateway hostname in your connection string. Instead, there is an option you can set when initializing your client to do that.

If you are trying to communicate with a custom gateway that handles MQTT communication itself and then does some translation to communicate up to IoT Hub, then we don't really support that scenario. That said, if the only change you've needed to make to enable your scenario is to remove that ```isEdgehub``` flag you highlighted, then you may be able to just provide your gateway's hostname in the regular hostName field in your connection string. Something like "HostName=your-custom-gateway.net;DeviceId=YourDevice;SharedAccessKey=XXXXXX". The SDK will connect to the gateway hostname if it is provided or it will connect to the regular hostname. Between the two scenarios, the only difference within the SDK is what topics it will subscribe to (as you've noticed).

As for the C2D messages being cleared, the SDK actually does subscribe to C2D messages by default even if you didn't provide a handler. This behavior isn't great, and we'd like to change it, but it would be a breaking change. The only workaround right now is to make sure you set your client's C2D message handler before you open your client.

**Comment by zonble** [comment]
Hi,

thanks for your reply!

When I read the documentation [How an IoT Edge device can be used as a gateway](https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-as-gateway?view=iotedge-2020-11), I did not realize when a device behind a gateway would become an edge hub. it said there are "IoT device", "IoT behind a gateway", "IoT Edge device" and "IoT Edge behind a gateway". It left me an impression that my devices would be "IoT behind a gateway" if I set geteway hostname in the connection string, and the devices could still receive C2D messages, and there is somewhere else to set a device as an edge hub like the Azure portal.

![Screenshot_2022-06-21_10-02-05](https://user-images.githubusercontent.com/53011/174701744-db43a3e7-e443-4657-9578-f770ff8d31b0.png)

The page did not describe how to set the connection strings for these device types. Maybe Microsoft can update the page? Thanks again. :)
