### ISSUE TITLE
[Technical Question] Connect directly using TPM without using edgeHub on a provisioned device

### ISSUE THREAD

**Issue by emilm** [Azure/azure-iot-sdk-java#1581]
Hello! I have some issues with edgeHub and I want to bypass it completely.
I have containers using ModuleClient:

```
var unixDomainSocketChannel = new UnixDomainSocketChannelImpl();
var client = ModuleClient.createFromEnvironment(unixDomainSocketChannel, setup.protocol);
...
```
This probably makes it connect via edgeHub.
For me edgeHub is a point of failure and it will conceal whether my device is connected or disconnected. I need the events for when it is disconnected / connected. This happens on poor connections a lot.

1. Is there a way to connect directly still using TPM?
2. What impact will it have on storage of messages, TTL / Lifetime when being offline? Is the queue system preserved or is that in edgeHub?

Thanks!

**Comment by timtay-microsoft** [comment]
There is no direct way to construct a moduleClient instance that uses the TPM for getting authentication credentials that then connects to IoT hub directly instead of to your Edgehub. However, it should be possible to alter your module's environment variables to make it connect to IoT hub. If you remove or set to "" the envirornment variable [IOTEDGE_GATEWAYHOSTNAME](https://github.com/Azure/azure-iot-sdk-java/blob/9a786b55d798d426b24e649c9cad05d975e95eae/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java#L49) then your module should connect to IoT Hub. 

> What impact will it have on storage of messages, TTL / Lifetime when being offline? Is the queue system preserved or is that in edgeHub?

The SDK still has local message queueing like it would have when connecting to Edgehub. That local message queueing allows you to [set an expiry time](https://github.com/Azure/azure-iot-sdk-java/blob/9a786b55d798d426b24e649c9cad05d975e95eae/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/Message.java#L368) after which the SDK will report that the message did not send the message before the timeout.

**Comment by emilm** [comment]
@timtay-microsoft  Thanks for your answer! Exactly what I am looking for.,
Is the local message queue persistent across reboots (not in memory)? Where does it know where to store it?

**Comment by timtay-microsoft** [comment]
The SDK's local message queue is stored in memory so it does **not** persistent across reboots.

**Comment by timtay-microsoft** [comment]
Did you need any further help on this @emilm?

**Comment by emilm** [comment]
@timtay-microsoft  Thank  you for your answer. Unless I can somehow plug in my own queue store, I guess I have to stick with edgeHub. The reason is that I have gotten into some weird edge cases where it is online but is unable to receive any messages, while the internal connection from the SDK to edgeHub is fine.

**Comment by timtay-microsoft** [comment]
Gotcha.

For what it's worth, the SDK does notify you of all the messages it had queued when you close the client, so it should be possible to build a hardware-stored queue and fill it with the CANCELLED_ON_CLOSE messages. With that hardware persistence, you can reboot, instantiate a new device client, and enqueue all the messages that failed to send last attempt.

**Comment by timtay-microsoft** [comment]
> The reason is that I have gotten into some weird edge cases where it is online but is unable to receive any messages, while the internal connection from the SDK to edgeHub is fine.

This may be a bug in Edgehub or this SDK. If you see anything suspicious in the logs of either, feel free to file a bug about it here or on the [Edgehub repo](https://github.com/Azure/iotedge/issues).

For now, though, I'll go ahead and close this thread since the title's question has been answered.
