### ISSUE TITLE
Android MQTT Receiving Duplicate Messages

### ISSUE THREAD

**Issue by stevensharar** [Azure/azure-iot-sdk-java#1603]
Hello, 

I am using the android sample to receive device messages and I keep getting duplicate messages from the MessageCallback even though the message was only sent once. 

The device I am using as an IOT device is a Android 8 device, JAVA 1_8. I am sending the message from a Blazor Web App and I receive the message just fine on the device, but sometimes I receive the message again 20 to 30 minutes later. 

SDK Version: 'com.microsoft.azure.sdk.iot:iot-device-client:2.1.1'

Half of the time I receive the message once on the device, and the other half I get the same message twice. I am using azure IOT hub to communicate with a device remotely. It is critical that I only receive the message once when I send it because the message I am sending is initiating a remote control connection/service to control the device from the web interface. I can check for duplicate messages myself but I won't know if the message was duplicated by IOT or if the user wants to initiate another remote control session. 

Is this an issue with MQTT? Should I try a different protocol. My code to receive the message is exactly like the example with the only difference being the connection string.

**Comment by timtay-microsoft** [comment]
Generally, this only happens if IoT hub does not receive the acknowledgement sent by the SDK when the [message received callback returns](https://github.com/Azure/azure-iot-sdk-java/blob/62e12a003d6f63e02c04fd00228d1e3013cd951f/device/iot-device-samples/android-sample/app/src/main/java/com/iothub/azure/microsoft/com/androidsample/MainActivity.java#L160). If this behavior consistently happens, then it could be a bug. However, if it only sometimes happens, it could just be networking issues occasionally causing these acknowledgements to be lost. I'd be curious to hear if switching protocols helps you with this issue, but I wouldn't expect it to resolve network level issues.

If you have the chance, could you provide some SDK logs from a case where you saw this behavior?

In general, though, all messaging to and from IoT hub is QoS 1 ("at least once" not "exactly once") meaning you should anticipate duplicate messages from time to time and have some redundancy checking in your handlers. For example, cache a set of message Ids of received cloud to device messages so that you can see if a newly received message was already handled.

**Comment by timtay-microsoft** [comment]
@stevensharar do you have any logs you can share that demonstrate this issue?

**Comment by timtay-microsoft** [comment]
Closed due to inactivity. Feel free to open a new issue if you are still running into this issue and please provide some logs from when you've repro'd
