### ISSUE TITLE
[feature request] Update documentation for v2

### ISSUE THREAD

**Issue by The-Funk** [Azure/azure-iot-sdk-java#1649]
**Is your feature request related to a problem? Please describe.**
The current documentation and sample applications for the Java SDK target v1.x.x but v2.x.x is the current major release and deprecates/removes/changes certain features from v1.x.x

**Describe the solution you'd like**
New documentation and samples when you have time.

**Describe alternatives you've considered**
Using v 1.x.x for now

Thanks!

**Comment by brycewang-microsoft** [comment]
Hi @The-Funk, thanks for bringing this to our attention! I believe the samples have been updated to use the V2 SDK along with the [effort ](https://github.com/Azure/azure-iot-sdk-java/commit/cf54ce6cc7a6c672e07dbb840e1164f5cffb2e64)of major version upgrading a few months ago. Is there any specific exceptions you are observing? 

That being said, I agree that some of the sample readme files are out-of-date and we will review and update them. Or, if you are referring to other "documentations" here, feel free to share the relevant links so that we can understand what to address. Thanks!

**Comment by The-Funk** [comment]
@brycewang-microsoft I might need to look into the documentation and samples here. I was looking at the examples on the Microsoft learning site [here](https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-java-java-twin-getstarted)

**Comment by The-Funk** [comment]
Sorry to ask an extra question while I'm here but I also had a curiosity regarding V2. In V2, when updating device twin desired properties, is the entire twin sent to iothub or are changes sent as patches?

So if I update a single twin desired property, does the service SDK send just the updated property to iothub or is the entire twin desired packaged and sent?
