### ISSUE TITLE
Could not validate self signed certificate in Azure

### ISSUE THREAD

**Issue by buddhidesilva** [Azure/azure-iot-sdk-java#182]
HI Team,

I am trying to use X509 certificates whith IOT devices in Azure IOT hub.
I am using a self signed certificate for my development, testing purposes.

I have followed documentation available at : https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started

I have created a self signed certificate using openssl commands and added it's digital signature to the azure certificates as described in above documentation.

I have a confusion about the verification process of it.
Once I generated the verification code, In the portal it says : "Use this code as the CN value in the subject of a new leaf certificate and upload the resulting certificate in order to verify"

Does this mean to create a new key pair and create digital signature of it using the self signed certificate's (which I have uploaded to certificates) private key ?

Note : I cannot run the powershell scripts since I am running on the linux environment + client wants them to be created using plain openssl commands.

I have used following commands when creating certificates for above scenarios,

Creating Self signed certificate,

```
openssl genrsa -out mykey.pem 2048
openssl req -new -sha1 -key mykey.pem -out mycsr.csr
openssl x509 -req -sha1 -days 365 -extfile v3.ext -in mycsr.csr -signkey mykey.pem -out mycert.pem
```

Content of v3.ext is as follows,

```
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
```

I have uploaded mycert.crt which produced by above command to certificate section in Azure IOT Hub.
Then created another keypair and signed it with mykey.pem (self-signed certificate's private key) as follows,
Note : When creating the CSR, I have used the validation code that is generated in Azure portal as the Common Name.

```
openssl genrsa -out myleafkey.pem 2048
openssl req -new -sha1 -key myleafkey.pem -out myleafcsr.csr
openssl x509 -req -sha1 -days 365 -extfile v3.ext -in myleafcsr.csr -signkey mykey.pem -out myleafcert.pem
```

Finally uploaded myleafcert.pem as the verification crt to the portal and when I click the verify button, It did not resolved it properly. It is giving me following error,

`Proof-Of-Possession failed. Issuer certificate 'E=buddhi_desilva@gmail.com, CN=Buddhi, OU=IOT, O=Aepona, L=Colombo, S=Western, C=LK' cannot be found in the certificate chain. If you contact a support representative please include this correlation identifier: bb7d440e-0033-468c-99c3-fff8455cce99, timestamp: 2017-11-28 19:21:17Z, errorcode: IH400053.`

Am I doing anything wrong here ?

**Comment by jspaith** [comment]
>  I cannot run the powershell scripts since I am running on the linux environment + client wants them to be created using plain openssl commands.

We have also created a bash script which helps do a lot of the work for you, rather than you having to invoke openssl directly.

Please checkout the instructions at https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md, and there is a .sh & .cnf files in the same folder to get you started.

Could you please try proof of possession using these scripts as it hopefully should just work for you and if not, we'd want to focus our efforts clarifying the checked in scripts / docs.

**Comment by anhashia** [comment]
@buddhidesilva 
The error is coming because your **verification** certificate has Root CA chain missing. Looks like your verification certificate is a standalone certificate and not issued by Root CA.

Use instructions at 
https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md
on Windows 10 machine for **comparison** on how the verification certificate should look like.

**Comment by prmathur-microsoft** [comment]
@buddhidesilva please let us know if the above does not answer your question.

**Comment by prmathur-microsoft** [comment]
Closing this as I have not heard in a while. Feel free to reopen if you see any further issues.
