### ISSUE TITLE
Ensure JDK compact 3 compliance for embedded systems

### ISSUE THREAD

**Issue by jemackayoe** [Azure/azure-iot-sdk-java#200]
As this library is designed for IoT devices it should be built for embedded systems, therefore it should be compliant to JDK compact3 rather than SE.

The use of Log4J has been raised a few times and I will also bring it to the attention of the developers. Log4J uses java.bean.* classes which are not included in compact3 so this logging library should not be used. Also it is bad practice to hard code a dependency on any specific logging framework for a widely used library such as this, so a logging facade such as SLF4J should be used to prevent any fixed dependencies. This allows the developers of the production application to choose a logging framework or fit this library into an existing logging framework.

The use of logging frameworks and the way logging has been implemented has been raised many times and the developers do not seem to understand the importance or choose to ignore the requests from other developers - me included. It is very frustrating to spend so much time trying to fix a problem that should not exist!

**Comment by prmathur-microsoft** [comment]
@jemackayoe Thanks for raising logging issue again. I totally agree that we shouldn't use a particular logging library like log4j and move to more generic ones. Because of barrage of requests we receive we were not able to prioritize this until now. However I want to assure you that this is in our near term plans to make this change. I will keep you updated regarding it. Also keep an eye on our projects to see the progress https://github.com/Azure/azure-iot-sdk-java/projects/1

As per support for JDK compact3, we are investigating to see what kind of JDK should we add support to. i.e compact or SE embedded or ME embedded and we will soon start adding support for them.

**Comment by timtay-microsoft** [comment]
Sorry for the long delay on this issue. Since we have now replaced Log4j with SLF4J, I wanted to come back to this issue. Are you still seeing any dependencies that are preventing Compact 3 compliance?

**Comment by pete-carey** [comment]
I, too, have a need for compact profile 3 compliance. I'm currently running the latest off of master in a compact-profile 3 environment. More testing is necessary, but things *appear* to be working. Thank you!

**Comment by timtay-microsoft** [comment]
Glad to hear it! We will look into including a check for this version of java during our normal build process so that we can maintain it in the future. I'm going to leave this issue open until we get that figured out.

**Comment by timtay-microsoft** [comment]
Closing this issue due to lack of attention

**Comment by az-iot-builder-01** [comment]
@jemackayoe, @prmathur-microsoft, @pete-carey, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
