### ISSUE TITLE
Log statements uses System.out in Mqtt class

### ISSUE THREAD

**Issue by Ken1S** [Azure/azure-iot-sdk-java#210]
- **OS and version used:** <VERSION> Windows 10

- **Java runtime used:** <VERSION> 1.8

- **SDK version used:** <VERSION> 1.9

# Description of the issue:

The class Mqtt uses System.out instead of log,
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java
see row 369 and 433

**Comment by prmathur-microsoft** [comment]
We are working on removing these print statements and in the meanwhile if you want to submit a PR I'll be happy to review.

**Comment by xnt** [comment]
@prmathur-microsoft submitted PR. Cheers!

**Comment by timtay-microsoft** [comment]
Looks good, @xnt We'll get that merged right away. Thanks for contributing!

**Comment by timtay-microsoft** [comment]
The fix for this has been checked in. It should be released within a week or two. Thank you for your patience!

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of Device Client 1.10.0, so I'm closing this issue for now. Feel free to re-open if you still see any issues.

@xnt @Ken1S, thank you for your contribution to our open-sourced project! Please help us improve by filling out this [2-minute customer satisfaction survey](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.surveymonkey.com%2Fr%2FQ5PLZ3V&data=02%7C01%7Ctimtay%40microsoft.com%7Cbfd772231c9c48abe82a08d5a0a66479%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636591558866731119&sdata=Eke9uU0qRn3tR%2BTFcP9yqLcv5dlcDfG%2F1owna8PhIno%3D&reserved=0)
