### ISSUE TITLE
[Device Client - MQTT] After connection reconnect, all messages return ERROR

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdk-java#219]
- **OS and version used:** Raspbian Jessie

- **Java runtime used:** 1.8

- **SDK version used:** iot-device-client 1.9.0

# Description of the issue:
After receiving a CONNECTION_DROP and reconnecting (less than a second later a CONNECTION_SUCCESS is received) all messages sent are returning ERROR.

# Code sample exhibiting the issue:
Just set up a client using a connection string + MQTT protocol and call subscribeToDeviceMethod(...), setMessageCallback(...), registerConnectionStateCallback(..) with any context object (or null context) and logging callbacks, then wait or provoke a connection drop + reconnect. Try to call sendEventAsync afterwards.

# Console log of the issue:
From state callback

> 2018-04-05 02:44:55,186 DEBUG: IoTHub connection state callback: CONNECTION_DROP
> 2018-04-05 02:44:55,864 DEBUG: IoTHub connection state callback: CONNECTION_SUCCESS

From IotHubEventCallback after calling sendEventAsync method:

> 2018-04-05 02:45:17,143 DEBUG: In result callback with status: ERROR

**Comment by timtay-microsoft** [comment]
Reconnection logic recently underwent a large overhaul that should fix this issue. We are planning to release these changes by 4/13. I'll update this thread when we do so that you can try it out.

**Comment by timtay-microsoft** [comment]
Can you try your scenario with Device Client version 1.10.0?

**Comment by pizerg** [comment]
In my opinion the API would be cleaner with two separate methods `setConnectionRetryPolicy` and `setMessageRetryPolicy`.

As for the scenario needing a longer timespan, any app/code that must be running continuously shouldn't be worried about the reconnection attempts stopping after 4 minutes by default. 

For example, before using Iot Hub we used Azure Service Bus, which simply reconnects whenever possible so we did not have to worry at all for the reconnection logic.

**Comment by timtay-microsoft** [comment]
Most of our customers are worried about excessive network usage. By having the default timeout set to 4 minute, we are protecting customers from using far too much of their data plans accidentally. I don't see the issue here as long as we provide the means to change this timeout to a practically infinite timeout.

As for the your suggestion to split the API up, we don't intend for those to be the only two actions that will ever need retry. We prefer to keep one API that all retry logic goes through rather than create X APIs for each different possible retriable scenario.

If you want the same behavior as Azure Service Bus, all you need to do is set the operation timeout to Long.MAX_VALUE and have your retry policy always retry (but with Exponential backoff still).

Since the original issue has been resolved, I'm going to close this issue for now. Feel free to re-open if it starts happening again, and feel free to provide a new issue for any enhancements you'd like to see.
