### ISSUE TITLE
Character '#' is not permitted in Device Twin property Keys

### ISSUE THREAD

**Issue by cacsar** [Azure/azure-iot-sdk-java#243]
# Description of the issue:
The [documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#tags-and-properties-format), [Service SDK](https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Pair.java#L24), and [Client SDK](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/Property.java#L24) are inconsistent with the service which does not permit '#' in Device Twin property keys.

# Repro Steps
Attempt to set a reported or desired property such as `m2(<#a` and observe failure resulting message transmitted by the IotHub service.
An example message is:
`{"errorCode":400004,"trackingId":[removed],"message":"Property or Tag name has invalid characters. Error in Property/Tag m2(<#a. Must not contain Control Characters, '.', '$', '#', or ' '.","timestampUtc":"2018-05-16T07:06:36.4096587Z"}`

**Comment by timtay-microsoft** [comment]
Good catch, we will make sure that the SDK prevents using characters like these in Twin properties

**Comment by cacsar** [comment]
To be clear I believe '#' is the only character that is missing, there is already a check (see the links in the description). It is possible the problem lies with the service not the SDK.

**Comment by timtay-microsoft** [comment]
Thanks for the clarification.

The service is correct about this. I believe our SDK and the documentation you found is out-of-date. The service likely added this restriction recently. They won't be adding support for twin properties with '#'

**Comment by timtay-microsoft** [comment]
Upon reconsideration, we will not be making any code changes around this scenario. Long term, we intend to not have checks on the device client SDK side for what characters are allowed or not. We will allow the service to dictate that to us, not the other way around. The service is correct in saying that those characters are not allowed.

Since there is nothing wrong with the error message that you are receiving, I'm going to go ahead and close this issue for now.
