### ISSUE TITLE
Need different retryPolicies for connectivity and sending messages

### ISSUE THREAD

**Issue by rkanubaddhi** [Azure/azure-iot-sdk-java#246]
- **OS and version used:** Windows 7 

- **Java runtime used:** 1.8 

- **SDK version used:** 1.11.0 

# Description of the issue:
I do not want to to retry sending the message if it is failed however I do want to connect back after a network disconnect. I want the DISCONNECT_RETRYING but not retrying to send the messages, is there any way to do this? 

I have NoRetry policy set on deviceClient and it is causing NoRetry on both connectivity and messaging

`deviceClient.setRetryPolicy(new NoRetry());`

**Comment by timtay-microsoft** [comment]
@jasmineymlo is correct. You can differentiate reconnection retry attempts from message retry attempts by looking at the lastException argument in a custom retry policy.

See the last few comments in [this discussion](https://github.com/Azure/azure-iot-sdk-java/issues/219)

Since we will not be adding a seperate API for each type of retryable event, I'm going to close this issue.

@rkanubaddhi thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
