### ISSUE TITLE
Java bindings in v2

### ISSUE THREAD

**Issue by adwk67** [Azure/azure-iot-sdk-java#326]
In iotedge v2 I cannot find a java bindings package. Is it still possible to write custom modules in java in v2 of iotedge? (and if so, are there any samples available) - and by that I mean using the same pattern as in v1 (extend GatewayModule), without having to use the IoT SDK directly?

Are java modules written for v1 compatible with v2, and, if not, what are the plans for backwards compatability in the future?

P.S. I originally asked this question here:
https://github.com/Azure/iotedge/issues/227

**Comment by JMayrbaeurl** [comment]
Yes. It's possible to develop custom modules in Java for Azure IoT Edge v2. The SDK has support for this since several weeks. Official samples and tooling is currently not available, but they are working on this. In the meantime you can take a look at my inofficial samples and tooling at https://github.com/JMayrbaeurl/azure-iotedge-java-samples

But I think you'll have to use the Client SDK directly for a custom module in Java. As far as I know v1 modules are not compatible with v2, and there are no plans for any kind of backward compatibility.

**Comment by adwk67** [comment]
Thanks for the feedback and for the link to your examples - very helpful!

**Comment by timtay-microsoft** [comment]
@adwk67 are you comfortable with me closing this issue? It sounds like you have the answer you were looking for

**Comment by adwk67** [comment]
Closing this issue.

**Comment by az-iot-builder-01** [comment]
@JMayrbaeurl, @adwk67, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
