### ISSUE TITLE
Java sends double escaped values in JsonPaylod of CloudToDeviceMethod to deviceSimulation

### ISSUE THREAD

**Issue by isaac-dasan** [Azure/azure-iot-sdk-java#327]
- **OS and version used:** <VERSION>  Windows 10

- **Java runtime used:** <VERSION>  JDk 8 u 181

- **SDK version used:** <VERSION>  iot-service-client:1.11.0

# Description of the issue:
We are using ScheduleDeviceMethodAsync in one of our services which creates a job. 
https://github.com/Azure/remote-monitoring-services-java/blob/ac99338c70c29bdaeb318061fa64ebe76041bef5/iothub-manager/app/com/microsoft/azure/iotsolutions/iothubmanager/services/Jobs.java#L109
For certain jobs we send empty CloudToDeviceMethod -> "{}" . Note that this is the same value("{}") that we are sending through both Java and Dotnet SDKs.

Once this call is made, our DeviceSimulation service gets notified and it tries to execute payload method. Before executing, it checks for empty values.
https://github.com/Azure/remote-monitoring-services-dotnet/blob/26b51212c591a433aea70845b7851d357c15e14d/device-simulation/Services/DeviceMethods.cs#L133

JobClient -> ScheduleDeviceMethodAsync  -> Dotnet SDK behaviour: 
DeviceSimulation gets methodRequest.DataAsJson = "null"

JobClient -> ScheduleDeviceMethod  -> Java SDK behaviour: 
DeviceSimulation gets methodRequest.DataAsJson = "\"{\"}"

# Code sample exhibiting the issue:

# Console log of the issue:

# Need Support?
* Have a feature request for SDKs? Please post it on [User Voice](https://feedback.azure.com/forums/321918-azure-iot) to help us prioritize.
* Have a technical question? Ask on [Stack Overflow](https://stackoverflow.com/questions/tagged/azure-iot-hub) with tag “azure-iot-hub”
* Need Support? Every customer with an active Azure subscription has access to support with guaranteed response time.  Consider submitting a ticket and get assistance from Microsoft support team
* Found a bug? Please help us fix it by thoroughly documenting it and filing an issue on GitHub (C, Java, .NET, Node.js, Python).

**Comment by timtay-microsoft** [comment]
I'm not sure that I understand the issue with the Java SDK here. If you invoke a method with the payload "{}", you should expect to receive a method invocation with a payload of "{}". The Java SDK does not force your method payload to be in json form, unlike the C# sdk. This allows you more flexibility when invoking and receiving methods.

If you want your method payload sent by the Java sdk to have no body, you simply invoke the method with a payload of "".

The only issue I see is that the C# sdk isn't parsing the "{}" correctly into json when receiving methods. I recommend that you look at the raw payload first by calling ```methodRequest.Data``` instead of ```methodRequest.DataAsJson```. The values seen there should be consistent regardless of which sdk sent them, as there will be no json parsing on the receiving end.

**Comment by isaac73** [comment]
Thanks @timtay-microsoft for the quick response. 

I checked again. Java SDK sends "\"{}\"". Dotnet SDK sends "{}" (which is what we send from our microservice)

**Comment by isaac73** [comment]
### Java SDK:

IOThubManager MS -> CloudtoDeviceMethod = `""`
DeviceSimulation MS -> methodRequest.DataAsJson = `"\"\""`


IOThubManager MS -> CloudtoDeviceMethod = `"{}"`
DeviceSimulation MS -> methodRequest.DataAsJson = `"\"{}\""`


### DOTNet SDK:

IOThubManager MS -> CloudtoDeviceMethod = `""`
DeviceSimulation MS -> methodRequest.DataAsJson != `"null"`


IOThubManager MS -> CloudtoDeviceMethod = `"{}"`
DeviceSimulation MS -> methodRequest.DataAsJson = `"{}"`


### Regarding your suggestion to use `methodRequest.Data`  instead of `methodRequest.DataAsJson` 

`methodRequest.Data` - is a byte array. I have to convert to Json anyway to look into it.

**Comment by timtay-microsoft** [comment]
Okay, I can see the issue better now, thanks for clarifying. I have created a [branch](https://github.com/Azure/azure-iot-sdk-java/tree/methodParserFix) with the preliminary fix for this issue. This fix will solve your problem, but can you build from this branch and test out it out to confirm?

**Comment by isaac73** [comment]
Sure

**Comment by timtay-microsoft** [comment]
@isaac73 did you get a chance to try out the branch I provided? Was it enough to unblock you once it is formally released?

**Comment by isaac73** [comment]
I did not. I couldn't do that because we are running on a earlier version. I have to replace a deprecated method and do some refactoring to test this fix. Right now I'm in the middle of a feature development.

**Comment by timtay-microsoft** [comment]
After doing some digging, it turns out that the Java SDK already provides you a mechanism to set the payload as json albeit not as a String like you are trying to do.

In this [sample](https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-samples/device-method-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/service/sdk/DeviceMethodSample.java) that demonstrates sending a basic Cloud to Device method, the payload object is in the form of a map, which the SDK can currently parse as json. The below code

```java
private static final Map<String, Object> payload = new HashMap<String, Object>()
{
    {
        put("arg1", "value1");
        put("arg2", 20);
    }
};
```

will translate on the receiving side as 

```
{"arg2":20,"arg1":"value1"}
```

So for your case, in order to mimic the C# sdk and send just "{}", you would use the following Java code:

```java
private static final Object payload = new HashMap<String, Object>()
{
    {
    }
};
```

Since this functionality is available in Service Client 1.11.0, you should be able to do this. Since this functionality is already available, I'm going to close this issue for now. Please let me know if you still have any issues with this.

**Comment by az-iot-builder-01** [comment]
@isaac73, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by isaac73** [comment]
@timtay-microsoft 

The sdk doesn't enforce that the CloudToDeviceMethod to be Map<String, Object>. Shouldn't it do this at a bare minimum?

Also, I think it's not good to have different SDK behavior between dotnet and Java. What do you think?

**Comment by isaac73** [comment]
In our use case, the UI will already the send the payload in `{"arg2":20,"arg1":"value1"}` format. Should I do foreach on this and reconstruct it in the above mentioned 'HashMap<String, Object>()' format? Seems NOT straight forward for me.

**Comment by timtay-microsoft** [comment]
The Java SDK does not enforce you send as a map because not all payloads need to be in a json format. We take all objects, not just json objects.

We are different from the C# sdk on this, you are right, but as long as you are still capable of sending the same payload, it isn't a pressing issue that you need to use slightly different code to do so.

During my investigation of this feature, I found several issues with parsing json out of a string like you are asking for. Using the map-based approach is much more reliable, so I urge you to use it instead.

**Comment by isaac73** [comment]
@timtay-microsoft Is there any doc on how to construct the payload. I don't see special instructions for Java [here](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.service.jobs._job_client.scheduledevicemethod?view=azure-java-stable). It will be helpful for devs.

**Comment by timtay-microsoft** [comment]
We don't have any special documentation on this yet, no. Is there some kind of payload that you are trying to form that you can't?

**Comment by isaac73** [comment]
My concern is that there must be some document which should talk about about this workaround/hack.

**Comment by timtay-microsoft** [comment]
Re-opening this issue for tracking purposes. We do intend to document this flow better

**Comment by timtay-microsoft** [comment]
The SDK now will avoid double-escaping json payloads, so I'm going to close this issue now, as there is no need to document this issue any further
