### ISSUE TITLE
[Device Client] DeviceMethodCallback message contains backslashes

### ISSUE THREAD

**Issue by soloxio** [Azure/azure-iot-sdk-java#378]
- **OS and version used:** Windows 10

- **Java runtime used:** 1.8

- **SDK version used:** 1.11.2

# Description of the issue:
When implementing DeviceMethodCallback for Client (by using Azure-IoT-SDK for java like [here](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/device-method-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceMethodSample.java)) in order to send the response back to IoT Hub, the message received by IoT Hub contains backslashes "\". These backslashes are before each double quotes in the payload. It makes the parser process failed.
Messages received by IoTHub with backslashes:

```
{
     "status": 123,
     "payload": "{\"abc\": \"xzy\"}"
}
```

I tried to use Azure-IoT-SDK for python and the payload are in json format (correct format). Then, of course the parser can execute successfully:

```
{
     "status": 123,
     "payload": {"abc": "xyz"}
}
```

Is there any way for Client to handle DeviceMethodCallback (java) to send the message like in python?

**Comment by soloxio** [comment]
Hello @timtay-microsoft: have you ever known this issue before?

**Comment by soloxio** [comment]
Is there anyone met this problem when using azure-iot-sdk Client (by java) ?

**Comment by timtay-microsoft** [comment]
I'm a little confused what you are asking about. What is the code snippet for your DeviceMethodCallback that is failing? And what parser process is failing?

**Comment by soloxio** [comment]
Hi @timtay-microsoft , do you have any suggestion or update about this issue?

**Comment by soloxio** [comment]
@timtay-microsoft : it's very helpful if you can give some suggestions for me about this topic.

Does anyone know (or meet) this issue while working with DeviceMethod (Client) using azure-iot-sdk for Java?

**Comment by maxtar** [comment]
@timtay-microsoft I've found where trouble.
/com.microsoft.azure.sdk.iot/iot-deps/0.7.2/e383024120af0d538d6f2b13f3e699e0b28ba92c/iot-deps-0.7.2-sources.jar!/com/microsoft/azure/sdk/iot/deps/serializer/MethodParser.java:381
This line looks like
```java
gson.toJsonTree(payload);
```
It call when payload not a map. DeviceMethodData class has two field:
```java 
int status;
String responseMessage;
```
response message - always string. And when called `gson.toJsonTree(payload);` it define payload as string and serialize it with backslashes.
It's a trouble...

**Comment by soloxio** [comment]
@maxtar  Have you found any way to get rid of the backslashes?
I think this problem only happen in Java with special "String" type, because we tried with other sdks (such as for C, python) they're ok

**Comment by maxtar** [comment]
@soloxio Yeah, we too. We also use C# and C clients. Problem only with java-client, because incorrect payload transformation to json as I described above.
Have no ability to delete backslashes instead of fix on sdk side.

**Comment by btanto** [comment]
Hi @timtay-microsoft i'm collaborating with @soloxio about this topic: we are fully blocked because of this issue. The only workaround we can implement is to build an alternative temporary client in Python/C/C# and switch back to Java client when fix is available, but this means more effort/time/money. 

Could you please give us asap a rough estimation for the fix? End of Jan19, end of Feb19 or even later?
This would help us a lot planning workitems for european winter holidays period.
Hope you'll understand our needs: thank you for your collaboration!

**Comment by prmathur-microsoft** [comment]
Sorry about the delay in providing a fix for this. At the moment because of holidays, progress has been slow. We plan to address this early next year and hopefully you will have a fix end of January.

**Comment by davilu** [comment]
@soloxio @maxtar Could you please confirm the bug is fixed? Thanks.

**Comment by btanto** [comment]
Hi @davilu, with @soloxio we have compiled an unofficial version of SDK with your first fix proposal (convert message to byte[] before sending to IoT. @soloxio team did this workaround during winter holidays, the result is ok for us (bug fixed) and we are still using it since then.
We then saw that the fix has been modified during january (more complex now).
At this moment we were waiting for a new official release on your side, to be included in our project.
We didn't plan to compile a new unofficial version so we cannot confirm that your new fix is ok for us.
If you need our confirmation BEFORE releasing a new official version, i will put in roadmap this activity but we can't give you a time estimation.

**Comment by maxtar** [comment]
@davilu Sorry for late answer. Will check.

**Comment by soloxio** [comment]
@davilu I confirm the bug is fixed in iot device new version 1.16.0
Thank you for the support.

**Comment by maxtar** [comment]
@davilu Works for me too. Thanx!

**Comment by btanto** [comment]
Thanks @davilu and @timtay-microsoft !

**Comment by timtay-microsoft** [comment]
Glad to here it works. Since this fix has been released as of Device Client 1.16.0 and Service client 1.16.1, I'm going to close this issue. Feel free to re-open if you still see any odd behavior around this new json parsing.

**Comment by az-iot-builder-01** [comment]
@soloxio, @maxtar, @btanto, @prmathur-microsoft, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by maxtar** [comment]
@az-iot-builder-01 ok :) Done
