### ISSUE TITLE
[Device Client] Library has too big footprint

### ISSUE THREAD

**Issue by mjcctech** [Azure/azure-iot-sdk-java#437]
# Description of the issue:
Device client is intended to run on device. Obviously there is always storage limitation and library for IoT should strive to limit it's dependency. Please consider following point:
* transport protocol in separated jar
* focus on biggest dependency - bouncy castle. It's size is over 3MB, almost half of all dependencies, and is almost used only for reading certificates and keys from pem.

**Comment by timtay-microsoft** [comment]
We agree with your points, and we do have this as a goal for the SDK

**Comment by mjcctech** [comment]
Great! Do you have schedule for implementing it? Moving reading certificate and key to separate library, that I can implement myself without bouncy castle would be small step in good direction.

**Comment by yzhong94** [comment]
@mjcctech do you have a goal in mind for the smaller footprint?  I agree that separating out the transport protocol is an obvious choice - it's about implementation timeline only.  We will likely not get to this before March/April.

**Comment by timtay-microsoft** [comment]
In the meantime, if you'd like to provide a PR for any of these goals, we'd be happy to review it and merge it in for you.

**Comment by TomSCommend** [comment]
Is there any progress or a new time plan for this issue?

**Comment by timtay-microsoft** [comment]
Sorry for the delay. We do have to maintain the ability to parse pem files within our sdk, but we are actively investigating the feasibility of removing the bouncycastle dependency and just implementing that pem parsing we got from them ourselves

**Comment by timtay-microsoft** [comment]
The current design of our SDK doesn't make it possible for us to split out the transport jars without substantial breaking changes. If a time comes where we re-do this SDK from the ground up, we'll set this as a goal. In the meantime, you can [manually exclude jars](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) that you know you won't need at runtime.

As for bouncycastle, we don't feel comfortable removing it as a dependency for this SDK. We don't have a good way to ensure that any logic we implement in this SDK won't break existing users. For users who want to remove this dependency themselves, they can manually exclude the dependency and provide the device client the SSLContext themselves by using [this constructor](https://github.com/Azure/azure-iot-sdk-java/blob/094c5c55a9dd40278d17b43ef7a15a99c834062b/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java#L230). By using that constructor, this SDK won't need to use bouncy castle at runtime.

Because of the above, I'm going to close this issue

**Comment by az-iot-builder-01** [comment]
@mjcctech, @TomSCommend, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
