### ISSUE TITLE
c2d messages feedback takes too long

### ISSUE THREAD

**Issue by cepxy** [Azure/azure-iot-sdk-java#544]
- **OS and version used:** Windows 10
- **Java runtime used:** OpenJDK Runtime Environment (Zulu 8.33.0.1-win64) (build 1.8.0_192-b01)
- **SDK version used:** iot-service-client-1.17.1

We are using the ito-service-client to send messages from our backend to the device via iot-hub.
We would like to receive a response about whether the message was received as soon as possible or an error if no response was made within a timeout.

However that seems not be possible or we are missing a point.

I set for instance feedbackReceiver.receive(15000) to set a timeout of 15 seconds. Mostly our messages are received immediately on the device. But the feedback always takes a very long time around 10 seconds to return a value.
Why is that so? Is that a mistake?
I would expect that I get feedback as soon as the device confirmed the message receive to the iot-hub and only get a negative feedback after the timeout if no confirmation was received from iot-hub.
If we set the timeout too small, we might miss the confirmation of the device, but if its set too high we have too much unnecessary waiting time.

Can this be fixed or is there another configuration we should use?

Here are some examples from the log with timestamps indicating send of the c2d message and receive feedback witha timeout set to 15000. The messages were received instantly on the device.
deliveryAcknowledgement is set to Full

14:41:49.939 DEBUG [http-nio-8090-exec-2  ]                    service.IoTHubService - Send message with id '18e39ab2-4229-4fc4-a623-6c45d983705b' to gateway ...
14:41:59.301 DEBUG [http-nio-8090-exec-2  ]                    service.IoTHubService - received FeedbackBatch from IoT-Hub with 1 records.

14:42:34.002 DEBUG [http-nio-8090-exec-8  ]                    service.IoTHubService - Send message with id '003d9b06-6103-4d84-a3ff-004beb6b6f89' to gateway ...
14:42:44.394 DEBUG [http-nio-8090-exec-8  ]                    service.IoTHubService - received FeedbackBatch from IoT-Hub with 1 records.

14:43:38.490 DEBUG [http-nio-8090-exec-4  ]                    service.IoTHubService - Send message with id '0ff53366-6cc9-4ff3-8227-41284244660b' to gateway ...
14:43:44.483 DEBUG [http-nio-8090-exec-4  ]                    service.IoTHubService - received FeedbackBatch from IoT-Hub with 1 records.

Thanks in advance

**Comment by timtay-microsoft** [comment]
This is expected behavior. When you make the call

```java
feedbackReceiver.receive(15000);
```

You are telling the SDK to listen for any message feedback for 15 seconds, and at the end of that 15 seconds, it will report all of the feedback that was received over that 15 second span. If you want more immediate feedback, then you need to wait for fewer than 15 seconds at a time.

**Comment by timtay-microsoft** [comment]
@cepxy do you need any further help on this issue?

**Comment by cepxy** [comment]
Hi and thanks for reply.
I get your point about the expected behaviour. But that does not solve my problem.

Still the question is: how can I send a message and get a result as soon as the device confirmed the receive of the message?

**Comment by timtay-microsoft** [comment]
Currently, the SDK doesn't support getting the feedback as soon as it happens. The way you are currently using the feedback receiver is the only way to get feedback. We currently don't have any plans to change the feedback receiver, but if you are willing to provide a PR with this feature, I'd be happy to review it for you.

If you are looking for a way to send information to a device and to have the service sdk get the result immediately, I strongly suggest using methods rather than C2D messages. The call to invoke a method on a device blocks until the device responds and allows you to receive information from the device.

**Comment by timtay-microsoft** [comment]
@cepxy do you still need help understanding how message feedback works?

**Comment by cepxy** [comment]
Thanks for clarification. I will take a closer look at direct methods. 
The topic can be closed then.
Regards

**Comment by az-iot-builder-01** [comment]
@cepxy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
