### ISSUE TITLE
Eclipse usage - Use standard package names to avoid package declaration errors

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/azure-iot-sdk-java#55]
- **OS and version used:** Windows 10 

- **Java runtime used:** 1.8 

- **SDK version used:** 1.0.21 

# Description of the issue:
When using Eclipse or the Spring Tool Suite the test classes can't be compiled without errors, because some are using the wrong package declarations in their source code file. Eclipse will show the following error 'The declared package "com.microsoft.azure.sdk.iot.device.transport.mqtt" does not match the expected package 
 "tests.unit.com.microsoft.azure.sdk.iot.device.transport.mqtt"'.

# Code sample exhibiting the issue:
E.g. the test class tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceTwinTest.java has the following package declaration in its source file:

package com.microsoft.azure.sdk.iot.device.transport.mqtt;

And Eclipse is expecting:

package tests.unit.com.microsoft.azure.sdk.iot.device.transport.mqtt;

Neither Maven, the Java Compiler nor IntelliJ IDE have a problem with this wrong usage of package declaration. Unfortunately Eclipse does and it can't be configured to ignore these errors.

The best way to solve this problem is to remove the additional prefix 'tests.unit' and put the test classes in the same folder hierarchy as the main classes.

# Console log of the issue:

**Comment by prmathur-microsoft** [comment]
We are investigating options for eclipse to work with our SDK. We will update you as and when we find a fix for this issue.

**Comment by jimbouki** [comment]
Why not just but the files in the appropriate packages. You claim the usage is wrong then why not fix it?  I am confused. This is not very hard to fix. If I have permission to pull request I would do it myself.  Please allow me to fix.

**Comment by jimbouki** [comment]
The problem came back with tests.unit.com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTest. It is not a deal breaker but I often find myself having to hack the code so it is not all red in eclipse and then stash and unstash when needed. Nevertheless, an IDE that does not scream at you, which is what I suspect even though I can likely find out from your gitignore file, is not a good IDE. I am sorry for my sharpness but this should not be the norm. If the IDE is screaming red I blame the code. The code should be in pristine condition when presented to any IDE industry standard IDE such as Eclipse.

**Comment by prmathur-microsoft** [comment]
This issue is now fixed as of check in - 4c5ce0979f108a58370006b1d1b3d5f94fa0b40d

**Comment by prmathur-microsoft** [comment]
Maven package containing the fix is released now. Please give it a try and feel free to reopen if you see further issues.
