### ISSUE TITLE
Android  Fileupload fails when using WorkerManager

### ISSUE THREAD

**Issue by ajmeraaxesh** [Azure/azure-iot-sdk-java#710]
Hi,
I am using Android WorkerManager to upload files to the Azure Storage and I get the following exception, when doing the fileupload 2nd time. 

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3896f61 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@77a2a86[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
    IotClientService  D  at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
    IotClientService  D  at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
    IotClientService  D  at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
    IotClientService  D  at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
    IotClientService  D  at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:664)
    IotClientService  D  at com.microsoft.azure.sdk.iot.device.fileupload.FileUpload.uploadToBlobAsync(FileUpload.java:130)
    IotClientService  D  at com.microsoft.azure.sdk.iot.device.DeviceClient.uploadToBlobAsync(DeviceClient.java:453)

- **OS and version used:** <VERSION> 

- **Java runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

# Need Support?
* Have a feature request for SDKs? Please post it on [User Voice](https://feedback.azure.com/forums/321918-azure-iot) to help us prioritize.
* Have a technical question? Ask on [Stack Overflow](https://stackoverflow.com/questions/tagged/azure-iot-hub) with tag “azure-iot-hub”
* Need Support? Every customer with an active Azure subscription has access to support with guaranteed response time.  Consider submitting a ticket and get assistance from Microsoft support team
* Found a bug? Please help us fix it by thoroughly documenting it and filing an issue on GitHub (C, Java, .NET, Node.js, Python).

**Comment by timtay-microsoft** [comment]
The SDK's ScheduledExecutorService should allow you to have multiple file uploads in progress at the same time since it has a max pool size of 10. Judging by that stacktrace though, the ScheduledExecutorService isn't accepting any more tasks at that point even though it has no active tasks. 

From the looks of it, the ScheduledExecutorService was shut down at some point. This can happen either when you close the device client yourself, or when the device client shuts down due to network connectivity issues. Is your device client being shutdown before you see this error?

**Comment by ajmeraaxesh** [comment]
I mean the way I have designed the code, I open the device client, I either send messages / upload file  and then close the client

and there is a scenario wherein I am sending message and calling upload file using WorkManager Chaining requests

so I my case, it would be opening client -> sending message -> closing client; opening client -> sending file -> closing client

Because I do not want to do my IoT tasks in the main thread of my Android App, I am using workmanager which uses background threads

**Comment by timtay-microsoft** [comment]
What protocol is your device client using? Is it AMQP, MQTT, or HTTPS? And if it is AMQP or MQTT, could you register the connection status callback on your device client? The connection status callback will tell you if the client closes itself due to some network issue. The callback isn't applicable if you are using HTTP though

**Comment by timtay-microsoft** [comment]
Closing this issue due to lack of customer activity

**Comment by az-iot-builder-01** [comment]
@ajmeraaxesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
